### ISSUE TITLE
<style> doesn't work

### ISSUE THREAD

**Issue by karak** [riot/custom-elements#1]
Style section doesn't work because it is just inserted under shadow-root like bellow:

```html
<body>
  <x-hello message="Good-bye!">
     #shadow-root
       <style>x-hello,[data-is="x-hello"]{ color: red; }</style>
       ...
  </x-hello>
</body>
```
Using `:host` rather than custom implementation would fix this.

APPEND:
This issue happened when passing compiled riot.tag, not RAW call of `define`.
For I suppose those use cases would be standard.
...Then,  the compiler should have some CSS switch to support shadow DOM.

**Comment by GianlucaGuarini** [comment]
Fixed in the riot-compiler@3.5.3. Thanks for reporting it

**Comment by karak** [comment]
Thank you. Simple `:host` is OK, but complex selector is still wrong.

```css
    :host {
      color: red;
    }
    .clicked {
      font-weight: bold;
    }
```

is compiled to:

```css
:host { color: red; } x-hello .clicked, [data-is="x-hello"] .clicked{ font-weight: bold; }
```
